We create a basic Multilayer Perceptron Regression Neural Network Model using matrix algebra and gradient descent concepts.

3 inputs each with 4 binary features (1,0,1,0), (1,0,1,1), (0,1,0,1) train the model for the target outputs 1,1,0 respectively 

We consider 1 hidden layer with 3 neurons and 5 different epoch values have been chosen for a single learning rate of 0.1.

We can see that the acuuracy of the model is increasing with increasing number of epochs. 

Happy Learning!

In [24]:
import numpy as np

#Input array - 3 observations with 4 features
X=np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])

#Output vetor
y = np.array ([[1],[1],[0]])

#Defining Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivative_sigmoid(x):
    return x*(1-x)

#Variable Initialization
epoch = [5,50,500,5000,10000]     #number of training iterations
lr = 0.1            #Learing Rate
inputlayer_neurons= X.shape[1]    #number of features in dataset
hiddenlayer_neurons = 3           #number of hidden layers neurons
output_neurons = 1                #number of neurons at output layer

#weight and bias initialization with random values
wh = np.random.uniform(size = (inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size= (1,hiddenlayer_neurons))
wout = np.random.uniform(size= (hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size = (1,output_neurons))

for j in epoch:
    for i in range(j):
    
        #Forward Propagation
        hidden_layer_input = np.dot(X,wh) + bh
        hiddenlayer_activation = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hiddenlayer_activation, wout) + bout
        output = sigmoid(output_layer_input)
    
        #Back Propagation
        E = y - output    #gradient of the erro
        slope_output_layer = derivative_sigmoid(output)
        slope_hidden_layer = derivative_sigmoid(hiddenlayer_activation)
        d_output = E*slope_output_layer
        Error_at_hidden_layer = np.dot(d_output, wout.T)
        d_hiddenlayer = Error_at_hidden_layer*slope_hidden_layer
    
        #Updating the weights for hidden layer and output layer
        wout += hiddenlayer_activation.T.dot(d_output)*lr
        bout += np.sum(d_output,axis=0, keepdims=True)*lr
        wh += X.T.dot(d_hiddenlayer)*lr
        bh += np.sum(d_hiddenlayer, axis= 0, keepdims=True)*lr
    
    print('\nOutput with Epoch = ',j)
    print(output)
    


Output with Epoch =  5
[[0.75601396]
 [0.76515003]
 [0.74297056]]

Output with Epoch =  50
[[0.68536655]
 [0.69163481]
 [0.66244946]]

Output with Epoch =  500
[[0.88134859]
 [0.84425538]
 [0.23435504]]

Output with Epoch =  5000
[[0.98464446]
 [0.97673551]
 [0.03263323]]

Output with Epoch =  10000
[[0.99146004]
 [0.9870346 ]
 [0.0180287 ]]


We see that the output is coming closer to the actual target values [1,1,0] with increasing number of iterations or 'epoch'